### ISSUE TITLE
Comparison of gw sites in saline lakes watershed with sites in gw conditions

### ISSUE THREAD

**Issue by msleckman** [USGS-VIZLAB/saline-lakes#42]
Reading in `historic_gw_site_info_unfiltered.rds` [gw conditions project ](https://github.com/USGS-VIZLAB/gw-conditions/blob/cfeec46aeaf19e21fc6a15b4c87620971c00fc9c/1_fetch.yml#L28-L33) - thx @lindsayplatt  for sending over the file directly - I am noticing that I have a few more sites than in gw conditions.

My sites are displayed on the map (`gw_sites_saline_lakes`) and there are 20 more than in the [gw conditions project](https://github.com/USGS-VIZLAB/gw-conditions) within the same extent.

![image](https://user-images.githubusercontent.com/36547359/203593459-6ae73c43-6e05-4828-b808-72a3005d2258.png)

vs gw conditions sites from `historic_gw_site_info_unfiltered.rds` (note that the layer is misnamed `gw_unfiltered...` - this is a typo). 
![image](https://user-images.githubusercontent.com/36547359/203593833-60d9d008-119f-4a8a-af89-fdcdd1838280.png)

and combined: 
 
![image](https://user-images.githubusercontent.com/36547359/203593979-51a6af1c-bbfc-4f81-8ca8-399ae865e7f0.png)

I took a closer took and noticed that the sites that don't exist in the list of gw sites in gw conditions rds file,  but exist in mine, do **not** have gw measurement (72019) with mean stat code (00003). They only have stat code : max (0002) and min (00001).

@ceenell @lindsayplatt  for the gw conditions project, did we intentionally exclude min and max gw measurements? did we only capture sites that collect  mean dv gw data?

**Comment by lindsayplatt** [comment]
Those sites may be excluded from our big historic pull if:

1. **The site doesn't have any groundwater data for the pcode `72019`** because we determined which parameter code to pull based on the state, not based on each site. So, the states you are using would have only had 72019 pulled ([here are where we define the alternatives](https://github.com/USGS-VIZLAB/gw-conditions/blob/cfeec46aeaf19e21fc6a15b4c87620971c00fc9c/0_config.yml#L63-L68)).
2. **The site doesn't have any `dv` service groundwater data with the `00003` stat code AND there is not any `uv` service data available to convert to a daily value.** We only pulled daily values when there was a mean (`stat_cd = 00003`) available. Otherwise, we pulled instantaneous data ([see logic function here](https://github.com/USGS-VIZLAB/gw-conditions/blob/cfeec46aeaf19e21fc6a15b4c87620971c00fc9c/0_historic/src/fetch_nwis_historic.R#L23)) and summarized to a mean daily value ([see function here](https://github.com/USGS-VIZLAB/gw-conditions/blob/cfeec46aeaf19e21fc6a15b4c87620971c00fc9c/0_historic/src/fetch_nwis_historic.R#L101)). If your site only reported min or max and didn't have any instantaneous data (`uv` service) available, it would be excluded.
3. **The site doesn't have any data available between 1900 and 2020.**
